name: mcpk-testing
author: Rebux
version: 1.0.0
main: de.nosswald.server.Plugin
commands:
  practice:
    aliases:
      - prac
    description: Toggle practice mode
  facing:
    aliases:
      - f
    usage: /facing <yaw> (<pitch>)
    description: Set precise facing
  parkour:
    aliases:
      - pk
      - jumpandrun
      - jnr
    usage: >
      /parkour start <id>
      /parkour leave
      /parkour add <name> <builder> <difficulty> <resetHeight>
      /parkour remove <id>
      /parkour list
    description: Manage parkour